# pytest.ini
[pytest]
log_cli = true
log_cli_level = DEBUG

addopts =
#    --collect-only
    -s
    -v
    -ra
    --strict-markers
    --tb=short

    --report-html

filterwarnings =
    ignore::pytest.PytestCollectionWarning
